### ISSUE TITLE
Running PM-api in webExtension

### ISSUE THREAD

**Issue by good-lly** [justinkalland/protonmail-api#2]
Hi!

Thank you for your project, but did you try or is there a way how to run this inside browser extension? Afaik I have setup webpack build for cross-browser extension but it finished on some Puppeteer issue with running "ws" / websockets ....

In general - my idea was to (thanks to your API) to send, receive and assign to folders specially formatted emails that contains data about events (maybe use some of well-known format mime/type) and make the extension that will work as Calendar fetching and parsing this data from private PM folder .... but I failed for now. 

Maybe, the workaround can be to wrap it inside the Electron container and make the desktop app?

<img width="871" alt="Screen Shot 2019-05-14 at 3 52 32 AM" src="https://user-images.githubusercontent.com/1671375/57693441-85251180-7649-11e9-8e80-513b4669ecdf.png">

**Comment by justinkalland** [comment]
I am going to close this old issue.

Support for this would be cool but outside the scope of the project right now.
