### ISSUE TITLE
Add Unread to Email

### ISSUE THREAD

**Issue by Den1al** [justinkalland/protonmail-api#3]
I found it very useful to have the `unread` field from the email.
This is already brought to us by the API:

```javascript
function isEmailUnread(email) {
    return email._data.Unread;
}
```

**Comment by justinkalland** [comment]
Better late than never!

I added [`email.isRead`](https://justinkalland.github.io/protonmail-api/Email.html), [`email.read()`](https://justinkalland.github.io/protonmail-api/Email.html#read), [`email.unread()`](https://justinkalland.github.io/protonmail-api/Email.html#unread)
